const fs = require('fs');
const path = require('path');
const { DEFAULT_CONTRACTS } = require('../config/contracts');
const contractVerifyService = require('./contractVerifyService');

const CONTRACTS_PATH = path.join(__dirname, '..', 'data', 'contracts.json');

function ensureContractsFile() {
  if (!fs.existsSync(CONTRACTS_PATH)) {
    fs.mkdirSync(path.dirname(CONTRACTS_PATH), { recursive: true });
    fs.writeFileSync(CONTRACTS_PATH, JSON.stringify(DEFAULT_CONTRACTS, null, 2));
  }
}

function readContracts() {
  ensureContractsFile();
  try {
    return JSON.parse(fs.readFileSync(CONTRACTS_PATH, 'utf8'));
  } catch {
    return [...DEFAULT_CONTRACTS];
  }
}

function writeContracts(contracts) {
  fs.mkdirSync(path.dirname(CONTRACTS_PATH), { recursive: true });
  fs.writeFileSync(CONTRACTS_PATH, JSON.stringify(contracts, null, 2));
}

function getContracts(filters = {}) {
  let contracts = readContracts();

  if (filters.status) {
    contracts = contracts.filter((item) => item.status === filters.status);
  }

  if (filters.chainId) {
    contracts = contracts.filter((item) => item.chainId === Number(filters.chainId));
  }

  if (filters.type) {
    contracts = contracts.filter((item) => item.type === filters.type);
  }

  return contracts;
}

function getContract(address) {
  const normalized = String(address || '').toLowerCase();
  return readContracts().find((item) => item.address.toLowerCase() === normalized) || null;
}

function reviewContract(address, payload, reviewer) {
  const contracts = readContracts();
  const index = contracts.findIndex(
    (item) => item.address.toLowerCase() === String(address).toLowerCase()
  );

  if (index === -1) {
    return { ok: false, message: 'Contract not found.' };
  }

  const updated = {
    ...contracts[index],
    status: payload.status || contracts[index].status,
    auditStatus: payload.auditStatus || contracts[index].auditStatus,
    notes: payload.notes ?? contracts[index].notes,
    verified: payload.status === 'approved' ? true : contracts[index].verified,
    lastReviewedAt: new Date().toISOString(),
    reviewedBy: reviewer?.email || 'unknown',
  };

  contracts[index] = updated;
  writeContracts(contracts);

  return { ok: true, contract: updated };
}

function addContract(payload, reviewer) {
  const contracts = readContracts();
  const exists = contracts.some(
    (item) => item.address.toLowerCase() === String(payload.address).toLowerCase()
  );

  if (exists) {
    return { ok: false, message: 'Contract already registered.' };
  }

  const contract = {
    address: payload.address,
    name: payload.name,
    type: payload.type || 'token',
    chainId: Number(payload.chainId) || 56,
    verified: false,
    auditStatus: 'pending',
    status: 'pending_review',
    lastReviewedAt: null,
    reviewedBy: reviewer?.email || null,
    notes: payload.notes || '',
  };

  contracts.push(contract);
  writeContracts(contracts);

  return { ok: true, contract };
}

function getChangelog() {
  return readContracts()
    .filter((item) => item.lastReviewedAt)
    .sort((a, b) => new Date(b.lastReviewedAt) - new Date(a.lastReviewedAt))
    .slice(0, 20)
    .map((item) => ({
      address: item.address,
      name: item.name,
      status: item.status,
      reviewedBy: item.reviewedBy,
      lastReviewedAt: item.lastReviewedAt,
      notes: item.notes,
    }));
}

const MAIN_APP_CONTRACTS_TS = path.join(__dirname, '..', '..', 'src', 'constants', 'contracts.ts');
const ADMIN_CONTRACTS_TS = path.join(__dirname, '..', '..', 'src', 'constants', 'adminContracts.ts');

function buildAdminContractsFile(contracts, syncedBy) {
  const approved = contracts.filter((item) => item.status === 'approved');
  const routers = approved.filter((item) => item.type === 'router');
  const tokens = approved.filter((item) => item.type === 'token');
  const syncedAt = new Date().toISOString();

  const lines = [
    '// Auto-generated by NovaFi Admin — do not edit manually',
    `// Last sync: ${syncedAt} by ${syncedBy || 'system'}`,
    '',
    'export interface AdminContractRef {',
    '  address: string;',
    '  name: string;',
    '  chainId: number;',
    '  type: "router" | "token" | "factory" | "other";',
    '}',
    '',
    `export const ADMIN_SYNCED_AT = "${syncedAt}";`,
    '',
    'export const ADMIN_APPROVED_ROUTERS: AdminContractRef[] = [',
    ...routers.map(
      (item) =>
        `  { address: "${item.address}", name: ${JSON.stringify(item.name)}, chainId: ${item.chainId}, type: "router" },`
    ),
    '];',
    '',
    'export const ADMIN_APPROVED_TOKENS: AdminContractRef[] = [',
    ...tokens.map(
      (item) =>
        `  { address: "${item.address}", name: ${JSON.stringify(item.name)}, chainId: ${item.chainId}, type: "token" },`
    ),
    '];',
    '',
  ];

  if (routers.length) {
    const primaryRouter = routers.find((item) => item.chainId === 56) || routers[0];
    lines.push(`export const ADMIN_PRIMARY_ROUTER = "${primaryRouter.address}";`);
    lines.push('');
  }

  return lines.join('\n');
}

function patchMainContractsTs(contracts) {
  if (!fs.existsSync(MAIN_APP_CONTRACTS_TS)) {
    return { ok: false, message: 'Main contracts.ts not found.' };
  }

  const primaryRouter = contracts.find(
    (item) => item.status === 'approved' && item.type === 'router' && item.chainId === 56
  );
  if (!primaryRouter) {
    return { ok: true, patched: false, message: 'No BSC router to patch.' };
  }

  let content = fs.readFileSync(MAIN_APP_CONTRACTS_TS, 'utf8');
  const routerPattern = /export const PANCAKE_ROUTER_V2 = "[^"]+";/;
  if (!routerPattern.test(content)) {
    return { ok: false, message: 'PANCAKE_ROUTER_V2 export not found in contracts.ts.' };
  }

  content = content.replace(
    routerPattern,
    `export const PANCAKE_ROUTER_V2 = "${primaryRouter.address}";`
  );
  fs.writeFileSync(MAIN_APP_CONTRACTS_TS, content);

  return { ok: true, patched: true, router: primaryRouter.address };
}

function syncToMainApp(reviewer) {
  const contracts = readContracts();
  const approved = contracts.filter((item) => item.status === 'approved');

  if (!approved.length) {
    return { ok: false, message: 'No approved contracts to sync.' };
  }

  const adminContractsContent = buildAdminContractsFile(contracts, reviewer?.email);
  fs.mkdirSync(path.dirname(ADMIN_CONTRACTS_TS), { recursive: true });
  fs.writeFileSync(ADMIN_CONTRACTS_TS, adminContractsContent);

  const patchResult = patchMainContractsTs(contracts);

  return {
    ok: true,
    syncedAt: new Date().toISOString(),
    approvedCount: approved.length,
    files: {
      adminContracts: path.relative(path.join(__dirname, '..', '..'), ADMIN_CONTRACTS_TS),
      mainContractsPatched: patchResult.patched,
    },
    patch: patchResult,
  };
}

async function verifyContractOnExplorer(address) {
  const contract = getContract(address);
  if (!contract) {
    return { ok: false, message: 'Contract not found in registry.' };
  }

  const verification = await contractVerifyService.verifyContract(
    contract.address,
    contract.chainId
  );

  if (!verification.ok) {
    return verification;
  }

  const contracts = readContracts();
  const index = contracts.findIndex(
    (item) => item.address.toLowerCase() === String(address).toLowerCase()
  );

  const notes = [
    contract.notes,
    `[${verification.explorer}] ${verification.recommendation}`,
    verification.contractName ? `Name: ${verification.contractName}` : null,
    verification.proxy && verification.implementation
      ? `Implementation: ${verification.implementation}`
      : null,
  ]
    .filter(Boolean)
    .join('\n');

  const updated = {
    ...contracts[index],
    name: verification.contractName || contract.name,
    verified: verification.verified,
    auditStatus: verification.auditStatus,
    notes,
    lastReviewedAt: new Date().toISOString(),
    reviewedBy: 'explorer-api',
  };

  contracts[index] = updated;
  writeContracts(contracts);

  return {
    ok: true,
    contract: updated,
    verification,
  };
}

module.exports = {
  getContracts,
  getContract,
  reviewContract,
  addContract,
  getChangelog,
  syncToMainApp,
  verifyContractOnExplorer,
};
